---
- name: set timezone
  file: src=/usr/share/zoneinfo/Europe/Moscow path=/etc/localtime force=yes

- name: add names to hosts
  lineinfile:
    dest: /etc/hosts
    line: '{{ item }}'
  with_items:
    - '{{ ngx_vip }} {{ ngx_name }}'
    - '{{ ngx01_ip }} {{ ngx01_name }}'
    - '{{ ngx02_ip }} {{ ngx02_name }}'
    - '{{ postfix_mail_ip }} {{ postfix_mail_name }}'
    - '{{ postfix01_ip }} {{ postfix01_name }}'
    - '{{ postfix02_ip }} {{ postfix02_name }}'
    - '{{ postfix03_ip }} {{ postfix03_name }}'
    - '{{ proxysql01_ip }} {{ proxysql01_name }}'
    - '{{ pxc1_ip }} {{ pxc1_name }}'
    - '{{ pxc2_ip }} {{ pxc2_name }}'
    - '{{ pxc3_ip }} {{ pxc3_name }}'
    - '{{ pcm1_ip }} {{ pcm1_name }}'
    - '{{ pcm2_ip }} {{ pcm2_name }}'
    - '{{ pcm3_ip }} {{ pcm3_name }}'

    - '{{ backup_ip }} {{ backup_name }}'

- name: Allow ssh password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
  tags: sshd_config

- name: sshd restart
  systemd:
    name: sshd
    state: restarted
  tags: sshd_config

- name: install general packages
  yum:
    name:
      - epel-release
      - vim
      - tcpdump
      - wget
      - libsemanage-python
      - libselinux-python
    state: latest
 
- name: Disable SELinux temporarly
  selinux: state=disabled

- name: Disable SELinux permanently
  replace:
    path: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    replace: 'SELINUX=disabled'