---
- name: Install elrepo-release
  yum:
    name: elrepo-release
    state: present

- name: Install packages
  yum:
    name:
      - pacemaker
      - corosync
      - pcs
      - fence-agents-all
      - psmisc
      - policycoreutils-python
      - resource-agents
  ignore_errors: yes

- name: Set password for user hacluster
  user:
    name: "hacluster"
    password: "$6$salt$0NKOQ3lvBadH426.fyRCGgkXnp2THG1aRLUgzVkRCEkAsj9deQPIua/1/qqV/1cbC2QNmy3MWLTQznbNWtg1F."
    state: present
    update_password: always
    create_home: yes

- name: Start pcsd service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - pcsd
############-----cut here-----############