---
- name: Install elrepo-release
  yum:
    name: "https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm"
    state: present

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: reboot
  reboot:

- name: Install packages
  yum:
    name:
      - kmod-drbd90
      - drbd90-utils
      - policycoreutils-python

- name: Set drbd_t to permissive
  selinux_permissive:
    name: drbd_t
    permissive: true

#- name: Reboot for avoid drbd-error
#  reboot:

- name: Add the drbd module
  modprobe:
    name: drbd
    state: present

- name: Disable drbd service
  systemd:
    name: drbd
    state: stopped
    enabled: no

- name: Create mountpoint
  file:
    path: "{{ postfix_drbd_mountpoint }}"
    owner: vmail
    group: vmail
    mode: '0757'
    state: directory
  tags: mount_drbd

- name: Configure drbd
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/drbd.d/{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - global_common.conf
    - pf_drbd.res

- name: Node is up?
  stat:
    path: /opt/drbd_node_done
  register: drbd_node_done

- name: Array init
  shell: "{{ item }}"
  with_items:
    - "drbdadm create-md {{ resource_drbd_name }} --force"
    - "drbdadm up {{ resource_drbd_name }}"
  when:
    - drbd_node_done.stat.exists != True

- name: Set replay protection (/opt/drbd_node_done)
  file:
    path: /opt/drbd_node_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - drbd_node_done.stat.exists != True
########---------cut here---------########
