---
- name: Install elrepo-release
  yum:
    name: elrepo-release
    state: present

- name: Install packages
  yum:
    name:
      - kmod-drbd90
      - drbd90-utils

- name: Reboot for avoid drbd-error
  reboot:

- name: Add the drbd module
  modprobe:
    name: drbd
    state: present

- name: Disable drbd service
  systemd:
    name: drbd
    state: stopped
    enabled: no

- name: Create mountpoint
  file:
    path: "{{ postfix_drbd_mountpoint }}"
    owner: root
    group: root
    mode: '0757'
    state: directory
  tags: mount_drbd

- name: Configure drbd
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/drbd.d/{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - global_common.conf
    - pf_drbd.res

- name: Node is up?
  stat:
    path: /opt/drbd_node_done
  register: drbd_node_done

- name: Array init
  shell: "{{ item }}"
  when: (drbd_node_done.stat.exists == False)
  with_items:
    - "drbdadm create-md {{ resource_drbd_name }} --force"
    - "drbdadm up {{ resource_drbd_name }}"

########---------cut here---------########
